services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: randompassword
    volumes:
      - pgdata:/var/lib/postgresql/data 
    ports:
      - 5432:5432

  web:
    build: .
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - db
 
  #adminer:
  #  image: adminer
  #  restart: always
  #  ports:
  #    - 8080:8080
 
volumes:
  pgdata:
  web: