version: '3.8'
services:
  app:
    image: nextjsapp:latest
    environment:
      - DATABASE_URL="postgres://postgres:postgres@db:5432/appdb?sslmode=disable"
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - '3000:3000'
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db: